# base
ENABLED = 1
DISABLED = 0
ERROR = -1


# debug
USE_GLOBAL_FILE_ONLY = True  # deprecated

TELEGRAM = 'telegram'
DISCORD = 'discord'

SUPPORTED_SCOPES = [TELEGRAM]


# Languages Handled for messages
ENG = 'eng'
ITA = 'ita'


# Messages type
REPLY = 0
AUDIO = 1
DOCUMENT = 2
ANIMATION = 3
IMAGE = 4
STICKER = 5
VIDEO = 6
VOICE = 7
VIDEO_NOTE = 8
CONTACT = 9
LOCATION = 10
VENUE = 11
TEXT = 12
COMMAND = 13


# Chat actions
NEW_GUILD_MEMBER = 0
LEFT_GUILD_MEMBER = 1
NEW_GUILD_TITLE = 2
NEW_GUILD_PHOTO = 3
DELETE_GUILD_PHOTO = 4
NEW_CHAT_CREATED = 5
PINNED_MESSAGE = 6
CONNECTED_WEBSITE = 7


# message max length for analyze
MEX_MAX_LENGTH = 70


# situational reply settings
AVOID_REPLY = 0
STD_REPLAY = 1
POWER_REPLAY = 2
STATIC_REPLAY = 3
STATIC_SPLIT_KEY = '&&&'
STATIC_SPLIT_MODE = '%%%'
STATIC_OVERRIDE_MODE = '!'


# CONFIGURATION SETTINGS
# prefix type
NO_PREFIX = -1
COMMAND_PREFIX = 0
OVERRIDE_PREFIX = 1
SUDO_PREFIX = 2

# global setting for auto reply _commands
DISABLED_MODE = 0
QUIET_MODE = 1
NORMAL_MODE = 2
SPAM_MODE = 3
AGGRESSIVE_MODE = 4

# module type, to define the _scope of the module
TYPE_LISTENER = 0
TYPE_COMMAND = 1


# ERRORS CONFIG
# message_reply_error
WRONG_STATIC_MODE_STRING = 1


# USER_DATA_LOG CONFIG
SAMPLE_STRING_LEN = 30
# Time spent to type
TIME_SAMPLE_VALUE = 11
# XP gain by message
XP_SAMPLE_VALUE = 12
XP_MAX_VALUE = 15

# BITS gain by message
BITS_SAMPLE_VALUE = 5
BITS_MAX_VALUE = 2
# XP for next level
XP_NEXT_LEVEL = 300
# User MESSAGE destination
MSG_DISABLED = 0
MSG_DIRECT = 1
MSG_ON_SAME_CHAT = 2
MSG_ON_STATIC_CHAT = 3

# COLORS
GRAY = (105, 105, 105)
GRAY_BLUE = (180, 180, 255)
DARK_GRAY = (62, 62, 62)
LIGHT_GRAY = (180, 180, 180)
LIGHT_GRAY2 = (230, 230, 230)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
BLUE = (0, 0, 255)
RED = (255, 0, 0)
GREEN = (0, 128, 0)

# Colors for print out data
DEFAULT_BACKGROUND_COLOR = DARK_GRAY
DEFAULT_TOP_TITLE_COLOR = LIGHT_GRAY2
DEFAULT_TEXT_COLOR = LIGHT_GRAY
DEFAULT_TOWER_1_COLOR = GRAY
DEFAULT_TOWER_2_COLOR = GRAY_BLUE
DEFAULT_TOWER_3_COLOR = GRAY_BLUE

DEFAULT_LEVEL_COLOR = LIGHT_GRAY2
DEFAULT_TITLE_COLOR = LIGHT_GRAY

DIR_DEFAULT_FONT = 'core/src/utils/fonts/helveticaneue-light.ttf'
